import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/navbar";
import { Providers } from "@/provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "รายการเมนูอาหาร",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
        </body>
    </html>
  );
}
